# Generated by Django 6.0.3 on 2026-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_etiqueta_tarea_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False, help_text='¿La tarea está completada?', verbose_name='Finalización de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, default=None, related_name='etiquetas', to='todolist.etiqueta'),
        ),
    ]
